name: CI - terraform-root
on:
  pull_request:
    branches: [main]
jobs:
  call-terraform-workflow:
    name: Terraform Checks
    uses: ./.github/workflows/terraform.yml
    with:
      path: .
  call-checkov-workflow:
    name: Security Analysis
    uses: ./.github/workflows/checkov.yml
    with:
      path: .
